spring:
  application:
    name: InventoryDev
  cloud:
     config:
       import-check:
         enabled: false
  data:
    mongodb:
      uri: mongodb+srv://jesuschumpitaz:InventoryDev@inventory.4jvtg.mongodb.net/InventoryDev?retryWrites=true&w=majority

server:
  port: ${SERVER_PORT:8090}
